GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "username": "M Fikri",
}

###
DELETE http://localhost:5000/users/2